### ISSUE TITLE
add tool for merge physics database to logic database.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#138]
**What would you like to be added**:

**Why is this needed**:

when user execute `show databases`,  we should show the tenant's logic databases to user, and if the the SQL is the `show databases where name=xxxxx` with condition, we should filter the logic databases.

https://dev.mysql.com/doc/refman/8.0/en/show-databases.html

**Comment by jjeffcaii** [comment]
dnt forget `show tables like 'ab_defg%'` 🤣

**Comment by ZLBer** [comment]
@dongzl @jjeffcaii  If no one does this, assign to me pls
