### ISSUE TITLE
Support "show columns from tables" SQL statement.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#182]
**What would you like to be added**:

**Why is this needed**:

`show columns from student;`

https://dev.mysql.com/doc/refman/8.0/en/show-columns.html

```
SHOW [EXTENDED] [FULL] {COLUMNS | FIELDS}
    {FROM | IN} tbl_name
    [{FROM | IN} db_name]
    [LIKE 'pattern' | WHERE expr]
```

**Comment by viviel** [comment]
Can you assign it to me?
