### ISSUE TITLE
add arana-ui project, support visual configuration.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#213]
**What would you like to be added**:

**Why is this needed**:

- [x] display `dataSourceClusters` details and edit config.
- [x] display `shardingRule` details and edit config, support add new table sharding rule.
- [x] display `tenants` details and edit config and add new tenant.
- [x] support  config `watch`, if user modify the config, it must push to arana.

**Comment by dongzl** [comment]
@chuntaojun

**Comment by chuntaojun** [comment]
![lQLPJxZo0CdhWD3NBaDNCgCwzejVR6aDGqgCrMrGF8DSAA_2560_1440 png_720x720g](https://user-images.githubusercontent.com/23445172/174418858-76ca904e-b546-48ed-8b64-2643b191038b.jpg)

**Comment by chuntaojun** [comment]
![企业微信截图_c35f51bb-7a67-4857-b7c6-3ed940e3a126](https://user-images.githubusercontent.com/23445172/174418907-6824ff2f-b4b0-4038-a6a7-6561c4dcc481.png)

**Comment by dongzl** [comment]
- [ ] display `dataSourceClusters` details and edit config.
- [ ] display `shardingRule` details and edit config.
- [ ] display `tenants` details and edit config.

**Comment by jjeffcaii** [comment]
The git repo is here https://github.com/arana-db/arana-ui
