### ISSUE TITLE
wireshark unable to use mysql protocol to analyze the data packet between client and ARANA

### ISSUE THREAD

**Issue by Penglq** [arana-db/arana#222]
**What would you like to be added**:

**Why is this needed**:

**Comment by jjeffcaii** [comment]
![image](https://user-images.githubusercontent.com/1284892/173507131-75752c93-3621-4a7f-994c-f84aadbb99cc.png)

Menu -> Analyze -> Decode As...
![image](https://user-images.githubusercontent.com/1284892/173507248-eee83dc7-b046-4a83-978c-b6a47b55e527.png)

![image](https://user-images.githubusercontent.com/1284892/173507519-202c8036-a24a-4231-828d-5ac3223d91a0.png)

**Comment by Penglq** [comment]
thank you
