### ISSUE TITLE
Refactor project package name.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#230]
**What would you like to be added**:

**Why is this needed**:

1. Move `testdata` to `test` and rename it to `mock`.
2. Rename `third_part` to `dependency`.

Do you think this is OK?

**Comment by jjeffcaii** [comment]
The 'testdata' folder is a standard practice in golang,we can found it in many famous projects.

**Comment by jjeffcaii** [comment]
In my opinion, no need to rename them.
