### ISSUE TITLE
Feature: Support SQL hint to solve no shard query condition cause table full scan.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#241]
**What would you like to be added**:

**Why is this needed**:

For this scenes:

`uid` is sharding key for table `student_xxxx`.

If user query data with `uid` condition, `arana` will auto route to the physics table.

But if user query data with no `uid` condition, It will cause table full scan.

Now, we want to support SQL hint, to make SQL route to the table which point out at the hint.

For example:

```
/*+ ARANA: SCAN=employee_*.student_0000 */
```

**Comment by jjeffcaii** [comment]
The basic hint backbone has been merged now, see #276

**Comment by jjeffcaii** [comment]
The final hint design:
  - empty arguments: `/*A! <YOUR_HINT_TYPE> */`
  - with arguments: `/*A! <YOUR_HINT_TYPE>(foo,bar,qux) */`

**Comment by jjeffcaii** [comment]
```sql
-- route to db0.tbl0 --
/*A! ROUTE(0,0) */ select * from student where name like 'Tom%'
```
