### ISSUE TITLE
Feature: Support multi-query for one query request.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#247]
**What would you like to be added**:

**Why is this needed**:

**Comment by baerwang** [comment]
what is the demand?

**Comment by dongzl** [comment]
https://dev.mysql.com/doc/internals/en/multi-statement.html

https://dev.mysql.com/doc/internals/en/multi-resultset.html

**Comment by baerwang** [comment]
使用 mulit query 提前要设置参数 multiStatements = true

**Comment by baerwang** [comment]
conn need support multi sql
