### ISSUE TITLE
start arana delete config output

### ISSUE THREAD

**Issue by baerwang** [arana-db/arana#248]
config output
![image](https://user-images.githubusercontent.com/52104949/175484608-9b441519-ea74-4648-b10c-95b0bf550626.png)
config not output
![image](https://user-images.githubusercontent.com/52104949/175484664-140e335f-b95f-499b-aa2a-a3d9181ba03b.png)

**Comment by jjeffcaii** [comment]
Maybe we can provide a env 'ARANA_DEV=1' to enable some diagnostic log just for developer.

**Comment by georgehao** [comment]
@georgehao
