### ISSUE TITLE
toBaseShow handle `from` or `in` error

### ISSUE THREAD

**Issue by baerwang** [arana-db/arana#332]
**What happened**:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/52104949/182568343-cedf222b-97b2-4898-86b8-24b00674b57f.png">

**What you expected to happen**:

The result is `from` not `in`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

`show table status from employees`

**Comment by baerwang** [comment]
assignees me

**Comment by dongzl** [comment]
@baerwang  This is the SQL grammar, we should all support.

https://dev.mysql.com/doc/refman/8.0/en/show-table-status.html

**Comment by baerwang** [comment]
toBaseShow 不怎么好操作

**Comment by baerwang** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/52104949/183324209-480820c9-062f-42cf-a1c1-b9ea38081598.png">

**Comment by dongzl** [comment]
ref #369
