### ISSUE TITLE
[SQL] Support `CHECK TABLE Statement`

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#386]
**What would you like to be added**:

**Why is this needed**:

https://dev.mysql.com/doc/refman/8.0/en/check-table.html

**Comment by baerwang** [comment]
assigness me

**Comment by baerwang** [comment]
<img width="800" alt="image" src="https://user-images.githubusercontent.com/52104949/191651357-fdc964c7-6be5-45c6-83d8-62b65686b49b.png">
parser not support sql
