### ISSUE TITLE
[Bug] run docker-compose up error

### ISSUE THREAD

**Issue by robbinhan** [arana-db/arana#392]
**What happened**:

report error message: `service "arana" depends on undefined service arana-admin: invalid compose project` that when `docker-compose up`

**What you expected to happen**:

start arana service success

**How to reproduce it (as minimally and precisely as possible)**:

run `docker-compose up`

**Anything else we need to know?**:

nothing

**Comment by jjeffcaii** [comment]
Use the latest master version, it should include arana-admin already.
