### ISSUE TITLE
[Bug] `SHOW TABLE STATUS FROM employees;` show arana core table

### ISSUE THREAD

**Issue by baerwang** [arana-db/arana#393]
**What happened**:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/52104949/187825835-fae00ceb-9366-40e6-aaa6-04ebea13366a.png">

**What you expected to happen**:
Same result as `show tables`

**How to reproduce it (as minimally and precisely as possible)**:
```sql
SHOW TABLE STATUS FROM employees;
```

**Anything else we need to know?**:
Provide filter, filter out uniformly arana core table

**Comment by jjeffcaii** [comment]
Need to hide those tables with prefix `__arana_`.

**Comment by robbinhan** [comment]
assignees me
