### ISSUE TITLE
[TRACE] add jaeger into docker-compose.yml

### ISSUE THREAD

**Issue by jjeffcaii** [arana-db/arana#429]
Need to add jaeger into docker-compose.yml for local development.
Currently, we will get a message like `2022/09/26 20:53:29 Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused`.

**What would you like to be added**:

**Why is this needed**:

**Comment by binbin0325** [comment]
@binbin0325 will solve it

**Comment by dongzl** [comment]
ref #443
