### ISSUE TITLE
[BUG]docker-compose.yaml

### ISSUE THREAD

**Issue by XdpCS** [arana-db/arana#442]
**What happened**：When I exec `docker-compose up -d`, and I did not pull MySQL.This error was `no matching manifest for linux/arm64/v8 in the manifest list entries`

**Anything else we need to know?**: This way works for me on M1 with Docker, and this way can pull MySQL.
<img width="490" alt="image" src="https://user-images.githubusercontent.com/72180730/194309702-18ec3d45-f16a-4c16-99dd-a62dcd89f038.png">

**Comment by baerwang** [comment]
this not bug,docker not support m1 mysql mirror,Need to compile x86 mysql on the platform

**Comment by XdpCS** [comment]
Thank you.
