### ISSUE TITLE
[Bug]  Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#443]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

when execute SQL, the console will print ` Post "http://localhost:14268/api/traces": dial tcp 127.0.0.1:14268: connect: connection refused`.

**Comment by jjeffcaii** [comment]
duplicated with #429
