### ISSUE TITLE
[SQL] Support MySQL `RAND` and `SIGN` function. 

### ISSUE THREAD

**Issue by BuYu-Wang** [arana-db/arana#453]
**What would you like to be added:**

**Why is this needed:**

official document:
https://dev.mysql.com/doc/refman/5.6/en/mathematical-functions.html#function_rand
https://dev.mysql.com/doc/refman/5.6/en/mathematical-functions.html#function_sign

reference code:

https://github.com/arana-db/arana/tree/master/pkg/runtime/function2/abs.go

**Comment by BuYu-Wang** [comment]
@BuYu-Wang

**Comment by dongzl** [comment]
ref #454
