### ISSUE TITLE
[SQL] Support MySQL `SQRT` and `EXP` function.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#457]
**What would you like to be added**:

**Why is this needed**:

ref #454 

official document:
https://dev.mysql.com/doc/refman/5.6/en/mathematical-functions.html#function_sqrt
https://dev.mysql.com/doc/refman/5.6/en/mathematical-functions.html#function_exp

reference code:

https://github.com/arana-db/arana/tree/master/pkg/runtime/function2/abs.go

**Comment by dongzl** [comment]
@胡绍洲

**Comment by raspberry-hu** [comment]
assign to me

**Comment by dongzl** [comment]
ref  #498
