### ISSUE TITLE
[SQL] Support MySQL `CONCAT` function.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#503]
**What would you like to be added**:

**Why is this needed**:

ref #454 

official document:
https://dev.mysql.com/doc/refman/5.6/en/string-functions.html#function_concat

code:
https://github.com/arana-db/arana/tree/master/pkg/runtime/function/scripts/string.js

reference code:

https://github.com/arana-db/arana/tree/master/pkg/runtime/function2/abs.go

**Comment by Charlie17Li** [comment]
please assign it to me, thx :)
