### ISSUE TITLE
【XA】build transaction log ability

### ISSUE THREAD

**Issue by chuntaojun** [arana-db/arana#555]
**What would you like to be added**:

build xa transaction log depend on mysql table

**Why is this needed**:

**Comment by xdusoy** [comment]
please assign the issue to me @dongzl

**Comment by chuntaojun** [comment]
https://github.com/arana-db/arana/blob/master/pkg/runtime/transaction/trx_log.go

**Comment by chuntaojun** [comment]
把上面这个文件按照接口和库表定义实现就好

**Comment by dongzl** [comment]
1、表可以自动创建成功
2、每个租户数据只能初始化一次
3、CRUD 接口逻辑正常

**Comment by maronghe** [comment]
看已经有 MR 合并了，是不是可以关了？

**Comment by maronghe** [comment]
done
