### ISSUE TITLE
[SQL] Support MySQL `alter table add index` grammar.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#582]
**What would you like to be added**:

**Why is this needed**:

https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

**Comment by mengchuang123** [comment]
![f122b65f3b2a0a16a4665396ec579ce3](https://user-images.githubusercontent.com/62008995/211196025-437db8dd-e8bc-4009-81e1-66ee29136471.png)
arana seems to already support this grammar.
