### ISSUE TITLE
What's the difference between arana and dapr?

### ISSUE THREAD

**Issue by jwcesign** [arana-db/arana#612]
They both can work as a sidecar proxy and can connect to different db.

**Comment by jjeffcaii** [comment]
Image that we have 8 tables user_0000~user_0007 in different mysql clusters, and there's a sharding key `uid` which can be used to compute target route table by `uid % 8`.

Now we want to query the row with uid=1:
1. Dapr: APP ---> Dapr SDK ----gRPC(I guess)---> Dapr mysql component ---> phy mysql. Think about which layer to compute the `uid % 8`? Maybe you need some work to implement the sharding layer.
2. Arana: APP ----> MySQL Driver ---> Arana ---> phy mysql. Here, arana implements the standard mysql protocol, and it also computes the table route.

Next, consider a more complex case like `select gender,avg(age) from user where uid between 20200000 and 20209999 group by gender`:
1. Dapr: Which layer should compute and do aggregate the result??? If could, how to provider an adhoc style? Maybe next query will be more complex.
2. Arana: you just submit SQL like a normal MySQL did, arana will handle it.

So, if you really want to implement Dapr with a sharding system, the best choice is using arana as the backend Dapr mysql component directly, your arch will be more like:
APP ---> Dapr SDK ---> Dapr mysql component ---> Arana ---> phy mysql

**Comment by jwcesign** [comment]
> APP ---> Dapr SDK ---> Dapr mysql component ---> Arana ---> phy mysql
Understand, thanks a lot
