### ISSUE TITLE
[SQL] implement local LIKE processor

### ISSUE THREAD

**Issue by jjeffcaii** [arana-db/arana#621]
Implement LIKE in local Arana instance, the APIs should be similar with codes below, I think.

```go
type Liker interface {
    Like(ctx context.Context, s string) bool
}

func NewLiker(pattern string) Liker {
     // ...
}

// For Example, when executing:  show tables like 'stu%'
liker := NewLiker("stu%")

liker.Like("student") // true
liker.Like("omz") // false

```

For the internal implementation, the [GLOB](https://en.wikipedia.org/wiki/Glob_(programming)) is recommended.

1. convert `stu%` to `stu*`, then calling the `filepath.Match(...)` in go std lib.
2. for a pattern like `fo_`, should be converted to `fo?`.

A spec case is `show tables like '%***%'`, maybe we can handle this following the steps below:
1. do `replace("*", "烫")`, got `%烫烫烫%`. (PS: same logical for other spec chars)
2. convert to GLOB, got `*烫烫烫*`.
3. for the input string `{"password":"********"}`, do step 1, got `{"password":"烫烫烫烫烫烫烫烫"}`.
4. then do the GLOB validation.

Finally, when the `Liker` was ready, we need to add integration with some SQL plan, such as `show tables like ...`, `show databases like ...`....

**Comment by jjeffcaii** [comment]
PS: GLOB is not the only choice, you can use Regexp, but it will be more complex I think.

**Comment by maronghe** [comment]
let me check, if any questions here, will discuess in this issue.

**Comment by maronghe** [comment]
hi @jjeffcaii , could you let me know more about this issue?

Q1: This `Like Func` will be in which folder or file? 
Q2: Will this func be used in the `SELECT` statement?

**Comment by jjeffcaii** [comment]
Be integrated with `SHOW TABLES LIKE 'st%'` first.
