### ISSUE TITLE
[SQL] Support `show sharding table from xxx`

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#629]
**What would you like to be added**:

**Why is this needed**:

`show sharding table from employee;`

- Task 1: SQL parser support this sql statement, reference: https://github.com/arana-db/parser/pull/9
- Task 2: Support sql statement at `arana` project, reference: https://github.com/arana-db/arana/pull/284

**Comment by mengchuang123** [comment]
I got it

**Comment by dongzl** [comment]
name
allow_full_scan
sequence-type
db_rules  json
tbl_rules  json
attributes  json
