### ISSUE TITLE
[SQL] when SQL has more ';' then return unexcpted result

### ISSUE THREAD

**Issue by maronghe** [arana-db/arana#641]
**What happened**:
When I run SQL `select * from student order by id ;;` in `mycli` command line. Got unexcepted result and command line can not exist.

**What you expected to happen**:

Clear results and errors? 🤔

**How to reproduce it (as minimally and precisely as possible)**:

1. Start arana server in local Mac. 
2. Connect arana using Mycli.
3. Run SQL `select * from student order by id ;;`

**Anything else we need to know?**:

**Comment by maronghe** [comment]
Thanks for pointing out @icrzye .

**Comment by jjeffcaii** [comment]
This is a bug caused by empty query, and it's not supported yet, I'll add a patch to fix it. Thanks for figure out.
