### ISSUE TITLE
[SQL] `SHOW xxx WHERE` SQL statment.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#672]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/5917359/232308659-db534b2e-340a-49ff-8fb4-9e15c84c6914.png">

```
SHOW DATABASES WHERE `name` = 'foobar';
SHOW TABLES WHERE `name` = 'student';
```

**Comment by jjeffcaii** [comment]
The local filter is not implemented yet.
