### ISSUE TITLE
[SEQUENCE] support CURRVAL,NEXTVAL for sequence in select statement

### ISSUE THREAD

**Issue by jjeffcaii** [arana-db/arana#675]
Scenario:
User can easily get a current/next sequence value over request a SQL below:

```sql
SELECT student.CURRVAL, student.NEXTVAL
```

Then, a row with current/next sequence value of `student` will be returned.
If the sequence `student` doesn't exist, an error will be returned.

Notice:
1. only match those SQLs contain `<sequence_name>.[CURRVAL|NEXTVAL]`, and no `FROM` followed.
2. use internal sequence API as implementation.
3. should handle alias, for example, `select student.NEXTVAL as xxxx`.
4. ...

**Comment by dongzl** [comment]
@宋志彬

**Comment by maronghe** [comment]
库级别的 sequencce
