### ISSUE TITLE
[Bug] fix `show tables xxx` statement error. 

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#677]
**What would you like to be added**:

**Why is this needed**:

<img width="432" alt="image" src="https://user-images.githubusercontent.com/5917359/235297255-cab34004-a4f6-48ad-951c-4dd5537e7a5a.png">

https://dev.mysql.com/doc/refman/8.0/en/show-tables.html

```
show full tables;  --error
show extended full tables;  --error
```

**Comment by RevSoy** [comment]
plz assign it to me

**Comment by maronghe** [comment]
@RevSoy How is the completion of this Issue?

**Comment by RevSoy** [comment]
I have no time to complete the issue recently, plz assign to other member, sorry🙏
@maronghe
