### ISSUE TITLE
[Test] add unit test for `/arana/pkg/boot`.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#706]
**What would you like to be added**:

**Why is this needed**:
<img width="439" alt="image" src="https://github.com/arana-db/arana/assets/5917359/ac298e63-5cdf-47fb-b253-c3d273cda31c">

add unit test for `/arana/pkg/boot` package, specifically for:

- discovery_import.go
- watcher.go

**Comment by csynineyang** [comment]
pls assign it to me
