### ISSUE TITLE
[Test] add unit test for `pkg/executor` and `pkg/merge`

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#709]
**What would you like to be added**:

**Why is this needed**:

add unit test for `pkg/executor` and `pkg/merge` package, specifically for:

- [ ] #758
- [x] pkg/merge/aggregator/init.go
- [x] pkg/merge/aggregator/load_agg.go

**Comment by Mulavar** [comment]
suspend the unit test of the development executor
