### ISSUE TITLE
[Test] add unit test for `/arana/pkg/runtime/namespace/...` package.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#746]
**What would you like to be added**:

**Why is this needed**:

add unit test for `/arana/pkg/runtime/namespace/...` package.

use this tools:
```
go test ./pkg/security/ -v -coverprofile=count.out

go tool cover -html=count.out
```

**Comment by csynineyang** [comment]
assign to me

**Comment by csynineyang** [comment]
github.com/arana-db/arana/pkg/runtime/namespace/command.go (74.1%)
github.com/arana-db/arana/pkg/runtime/namespace/namespace.go (80.3%)
