### ISSUE TITLE
Implement 'SHOW DATABASES' statement

### ISSUE THREAD

**Issue by jjeffcaii** [arana-db/arana#76]
**What would you like to be added**:
The `show databases` statement should only list those databases in the same tenant.
Please see the official manual, https://dev.mysql.com/doc/refman/5.7/en/show-databases.html

**Why is this needed**:
The database in ARANA means 'logical database' instead of 'physical database', we need to handle it.

**Comment by baerwang** [comment]
assignees me,me try learn

**Comment by baerwang** [comment]
Defined as row to return to the caller, database prefix 1 bytes from there take or generate ?

**Comment by baerwang** [comment]
![Uploading image.png…]()

**Comment by baerwang** [comment]
![image](https://user-images.githubusercontent.com/52104949/162978177-87fba996-f48f-4388-89c0-f69e8053b349.png)

**Comment by baerwang** [comment]
@jjeffcaii for help
