### ISSUE TITLE
Integrated go-mysql-server as embed MySQL test server.

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#96]
**What would you like to be added**:

Integrated go-mysql-server as embed MySQL test server.

https://github.com/dolthub/go-mysql-server

**Why is this needed**:

**Comment by dongzl** [comment]
refer：https://jasonkayzk.github.io/2021/02/15/%E4%BD%BF%E7%94%A8%E7%BA%AFGo%E5%AE%9E%E7%8E%B0%E7%9A%84MySQL%E6%95%B0%E6%8D%AE%E5%BA%93/

**Comment by Penglq** [comment]
I think it can be turned on when needed. 
https://toutiao.io/posts/8u7e71n/preview
