### ISSUE TITLE
'unknown error: no such logical database \x02employees'

### ISSUE THREAD

**Issue by dongzl** [arana-db/arana#97]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

1. Start server refer this PR comment: #90 .
2. Connect the server with mycli: `mycli -h127.0.0.1 -P13306 -udksl employees -p123456`
3. `show databases;`  is OK.
4. `use employees;` is OK.
5. `show tables;` is not OK.  error message: `(1105, 'unknown error: no such logical database \x02employees')`

<img width="517" alt="image" src="https://user-images.githubusercontent.com/5917359/159213928-5419e62c-6410-4d5a-bc4b-6ddca7a4a1a0.png">

**Comment by jjeffcaii** [comment]
Yup, that is a bug, confirmed. Will be fixed soon.
