### ISSUE TITLE
unable to use dksl login,must choose employees db?

### ISSUE THREAD

**Issue by baerwang** [arana-db/arana#98]
success
```shell
mysql -h192.168.200.161 -P13306 -udksl employees -p123456
```
error
```shell
mysql -h192.168.200.161 -P13306 -udksl -p123456
```

**Comment by jjeffcaii** [comment]
Should implement empty database connection. TBD.

**Comment by jjeffcaii** [comment]
The solution will be:
1. authorize login from global users, and considering if there are users with same username in different tenants.
2. handle query from database directly, for example `select * from some_db.some_table`.
3. handle `use some_db`.
