### ISSUE TITLE
ast convExpr judge empty fail

### ISSUE THREAD

**Issue by baerwang** [arana-db/arana#99]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/52104949/159611044-941499b7-1211-4352-b4b5-3f8c19184f5e.png">

**Comment by jjeffcaii** [comment]
bug, will be fixed soon.

**Comment by jjeffcaii** [comment]
Should be fixed since #105 was merged.
@baerwang  Pls confirm, thanks.

**Comment by baerwang** [comment]
LGTM
